### ISSUE TITLE
Course is unpublished but it is being treated as published

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-data-parser#116] opened 2021-01-04 20:55 UTC
Here is the course on production: https://ocwnext.odl.mit.edu/courses/18-s34-problem-solving-seminar-fall-2007/
It doesn't look like the course is published on the legacy system. It is listed as an archived course on a newer version of that course: https://ocw.mit.edu/courses/mathematics/18-a34-mathematical-problem-solving-putnam-seminar-fall-2018/

`1.json` shows that `last_unpublishing_date` is `None` and `workflow_history` shows that the course is still published. So I'm not sure if this is stale data, an error in Plone, or if there's something we are not checking that indicates an archived course.

**Comment by pdpinch** [comment] 2021-01-05 13:20
In which buckets(s) are you seeing this incorrect json data? QA? Prod?

**Comment by noisecapella** [comment] 2021-01-05 13:56
Prod

**Comment by pdpinch** [comment] 2021-01-14 20:59
I've confirmed that the status in Plone is "Archived" and, looking at the log, it should have been unpublished on 4/20/19. I guess I'll take a look in the bucket next. 

I wonder if there are other courses like this? @noisecapella how did you stumble on to this one?

**Comment by pdpinch** [comment] 2021-01-20 19:34
The raw JSON was not updated when the course was unpublished. This appears to be a bug in the Plone CMS. I opened an [issue to fix the CMS](https://github.com/mitocw/ocwcms/issues/238), but I might just do a quick pub/unpub cycle on this course to correct it.

**Comment by noisecapella** [comment] 2021-01-26 14:51
@pdpinch sorry I missed that question. I stumbled onto this looking at the media files which weren't downloaded correctly. I think this course was the only one with this particular problem. https://docs.google.com/spreadsheets/d/1XMxetrvq8qwRyJ9J6wWujKrrub9aW6o4R95ByPF20qk/edit#gid=0

**Comment by pdpinch** [comment] 2021-01-27 22:39
TIL that Plone won't allow you to change the state of an archived course, so fixing the CMS script doesn't help this particular course, even if it avoid the issue going forward. 

Instead, we've manually forced an export of the raw JSON from plone. The new data should arrive in the S3 bucket tomorrow, at which point we'll need to shepherd it through the full publication pipeline.

**Comment by pdpinch** [comment] 2021-01-29 13:25
I confirmed that the new parsed JSON arrived as expected, but it looks like [there is an issue with the build that doesn't clear out old courses](https://github.com/mitodl/salt-ops/issues/1357).

**Comment by pdpinch** [comment] 2021-02-01 13:30
The last issue here was the the build wasn't clearing out old content, which has been fixed by https://github.com/mitodl/salt-ops/commit/e86652129e5319cb19541238ae195a4b67074d59

Now we just need a proper 404 page...

**Closed as completed by pdpinch** 2021-02-01 13:30 UTC
Labels: bug
